### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CarlXK** [justeat/JUSTOKRs#2]
carl@carl-X:~/Projects/JUSTOKRs$ ember test
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
⠼ BuildingDEPRECATION: You're using legacy binding syntax: contentBinding="controller.keyResults" ('okr/templates/add-deliverable.hbs' @ L12:C10) . Please replace with content=controller.keyResults [deprecation id: ember-template-compiler.transform-old-binding-syntax]
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at raiseOnDeprecation (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1230:12)
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at invoke (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1338:7)
        at deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1291:32)
        at Object.deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:4186:37)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12331:28
        at each (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12350:7)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12316:7
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18703:7)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
DEPRECATION: You're using legacy binding syntax: selectionBinding="keyResult.content" ('okr/templates/add-deliverable.hbs' @ L15:C10) . Please replace with selection=keyResult.content [deprecation id: ember-template-compiler.transform-old-binding-syntax]
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at raiseOnDeprecation (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1230:12)
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at invoke (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1338:7)
        at deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1291:32)
        at Object.deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:4186:37)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12331:28
        at each (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12350:7)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12316:7
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18703:7)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
DEPRECATION: You're using legacy binding syntax: contentBinding="controller.teams" ('okr/templates/add-deliverable.hbs' @ L38:C10) . Please replace with content=controller.teams [deprecation id: ember-template-compiler.transform-old-binding-syntax]
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at raiseOnDeprecation (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1230:12)
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at invoke (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1338:7)
        at deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1291:32)
        at Object.deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:4186:37)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12331:28
        at each (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12350:7)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12316:7
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18703:7)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
DEPRECATION: You're using legacy binding syntax: selectionBinding="team.content" ('okr/templates/add-deliverable.hbs' @ L41:C10) . Please replace with selection=team.content [deprecation id: ember-template-compiler.transform-old-binding-syntax]
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at raiseOnDeprecation (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1230:12)
        at HANDLERS.(anonymous function) (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1322:7)
        at invoke (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1338:7)
        at deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1291:32)
        at Object.deprecate (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:4186:37)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12331:28
        at each (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12350:7)
        at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:12316:7
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18703:7)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
        at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)
        at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
        at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
Build failed.
File: okr/templates/add-deliverable.hbs
The Broccoli Plugin: [TemplateCompiler] failed with:
Error: Assertion Failed: Using `{{view}}` or any path based on it ('okr/templates/add-deliverable.hbs' @ L11:C8) has been removed in Ember 2.0
    at new Error (native)
    at Error.EmberError (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:4406:21)
    at assert (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:1390:13)
    at Object.assert (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:4170:34)
    at assertPath (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:11738:22)
    at /home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:11706:7
    at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18703:7)
    at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
    at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
    at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)
    at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
    at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
    at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)
    at visitors.ElementNode (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18719:16)
    at Walker.children (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18736:7)
    at Walker.visit (/home/carl/Projects/JUSTOKRs/bower_components/ember/ember-template-compiler.js:18704:12)

The broccoli plugin was instantiated at: 
    at TemplateCompiler.Plugin (/home/carl/Projects/JUSTOKRs/node_modules/broccoli-plugin/index.js:7:31)
    at TemplateCompiler.Filter [as constructor] (/home/carl/Projects/JUSTOKRs/node_modules/broccoli-persistent-filter/index.js:38:10)
    at new TemplateCompiler (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli-htmlbars/index.js:20:10)
    at TemplateCompiler (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli-htmlbars/index.js:12:12)
    at Object.registry.add.toTree (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli-htmlbars/ember-addon-main.js:31:16)
    at /home/carl/Projects/JUSTOKRs/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:26
    at Array.forEach (native)
    at processPlugins (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli-preprocess-registry/preprocessors.js:182:11)
    at module.exports.preprocessTemplates (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli-preprocess-registry/preprocessors.js:165:10)
    at EmberApp._processedTemplatesTree (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli/lib/broccoli/ember-app.js:802:48)
    at EmberApp.appAndDependencies (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli/lib/broccoli/ember-app.js:1033:24)
    at EmberApp.javascript (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli/lib/broccoli/ember-app.js:1159:34)
    at EmberApp.toArray (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:10)
    at EmberApp.toTree (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli/lib/broccoli/ember-app.js:1586:30)
    at module.exports (/home/carl/Projects/JUSTOKRs/ember-cli-build.js:23:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/home/carl/Projects/JUSTOKRs/node_modules/ember-cli/lib/models/builder.js:55:19)

**Comment by CarlXK** [comment]
carl@carl-X:~/Projects/JUSTOKRs/app/templates$ ember -v
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
ember-cli: 2.5.0
node: 5.10.1
os: linux x64
